server:
  port: 8086

spring:
  application:
    name: opwe-open-service
  cloud:
    nacos:
      discovery:
        server-addr: 101.200.41.70:8848
#  instance:
#    instance-id: opweOpenService01
#    prefer-ip-address: true

