server:
  port: 8090

spring:
  application:
    name: opwe-gateway-service
  cloud:
    #gateway settings
    gateway:
      discovery:
        locator:
          enabled: true
#      routes:
#        - id: opwe-data-process-service
#          uri: lb://opwe-data-process-service
#          predicates:
#            - Path=/opweDataProcessService/**
#
#        - id: opwe-open-service
#          uri: lb://opwe-open-service
#          predicates:
#            - Path=/opweOpenService/**
    #nacos settings
    nacos:
      discovery:
        server-addr: 101.200.41.70:8848
#  instance:
#    instance-id: opweOpenService01
#    prefer-ip-address: true

